# Numerical Python 

In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np 

In [3]:
np.array 

<function numpy.array>

In [4]:
c = np.array([[1,2,3],
             [4,5,6]])

In [5]:
c

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
c[0][2]

3

In [7]:
c[1][1]

5

In [8]:
c.shape

(2, 3)

In [9]:
c.ndim

2

In [10]:
c.sum()

21

In [11]:
c.min

<function ndarray.min>

In [12]:
c.min()

1

In [13]:
c.max()

6

In [14]:
c.transpose()

array([[1, 4],
       [2, 5],
       [3, 6]])

In [15]:
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])